### ISSUE TITLE
Class Acme\LaravelApi\Http\Controllers\WelcomeController does not exist

### ISSUE THREAD

**Issue by negativa** [daftspunk/oc-laravelapi-plugin#1]
The plugin does not work properly if your folders are named "Http/Controllers"
Rename the folder on the "http/controllers" and the plugin will work as follows

**Comment by daftspunk** [comment]
Fixed

**Comment by MaTToX3** [comment]
Sorry for commenting on this old issue but I would really like to know, why it doesn't work if you use Capitalize folder names? It works fine on Homestead but when deploying to production (also running Ubuntu) it throws the error as mentioned above. Is this OctoberCMS specific?
