### ISSUE TITLE
How to register custom middlewares

### ISSUE THREAD

**Issue by voveson** [daftspunk/oc-laravelapi-plugin#2]
I don't know if this is an appropriate place to ask, but I have not been able to find any documentation on registering custom middlewares.  I am developing an October plugin which also serves a RESTful API.  I have custom routing figured out, but we would like to be able to authenticate API requests using a custom middleware.  Can you provide some direction? Thank you!

**Comment by daftspunk** [comment]
Search google for "octobercms middleware" lead me here: https://github.com/octobercms/docs/pull/167/files

**Comment by voveson** [comment]
Thanks, @daftspunk -- I had seen [this post](http://octobercms.com/forum/post/how-to-register-middlewares-in-octobercms-plugin) in the OctoberCMS forum which leads to that same PR.  I just wasn't sure if that was considered the "official" solution.

**Comment by daftspunk** [comment]
Np, I think the `CmsController::extend` method is the likely candidate for official guidance.

```
Cms\Classes\CmsController::extend(function($controller) {
    $controller->middleware('your middleware here');
});
```

Added to the PR also.
