### ISSUE TITLE
Try to do extend from nav.blade.php

### ISSUE THREAD

**Issue by leonarpv** [daftspunk/oc-laravelapi-plugin#4]
Hi men

I  have some experience, but i try to do a extend from other file using that plugin, but not working.

I do my home.blade.php like that

```
<!DOCTYPE html>
<html>
<head>
    <title>Default</title>
<link href="bootstrap.css" rel="stylesheet">
</head>
<body>
@extends('nav')
</body>
</html>
```

and my nav.blade.php with

```
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

        <span class="sr-only">Toggle navigation</span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

      </button>



    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">

        <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-users fa-2x" aria-hidden="true"></i> CRM 
            </a>

            <ul class="dropdown-menu">

            <li><a href=""</a>Text</li>

          </ul>

        </li>


      </ul>

    </div><!-- /.navbar-collapse -->

  </div>

</nav>
```

and not found the blade file with that message

View [nav] not found. (View: /var/www/myproject/plugins/acme/laravelapi/views/home.blade.php)

**Comment by daftspunk** [comment]
Where does it look for nav I wonder?

**Comment by leonarandres** [comment]
sorry

I try extend from my home.blade.PHP to nav.blade.PHP with a @extends('nav') on the sale directory.
This is one simple example, but if i want to call nav from other is The same error

**Comment by leonarpv** [comment]
sorry

I try extend from my home.blade.PHP to nav.blade.PHP with a @extends('nav') on the sale directory.

The nav in theory, is looked on The top of The page.

This is one simple example, but if i want to call nav from other is The same error

**Comment by daftspunk** [comment]
Can you prepare an example plugin that shows the problem, perhaps we can find out what's wrong if we see the full picture.

**Comment by leonarpv** [comment]
it solved, it was silly the way he was doing with the extend,

I was doing initially extend with blade

`@extends('index')`

and the right way to do it with this plugin
`@extends('acme.laravelapi::index')`

Thanks Men..! @daftspunk
