### ISSUE TITLE
Session Persistence Not Working

### ISSUE THREAD

**Issue by grahambrown11** [daftspunk/oc-laravelapi-plugin#7]
We have a frontend built with Angular and Laravel Controllers that we are trying to get working in OctoberCMS. 
This project has been a good start, but assuming by the age there might be some differences with the latest OctoberCMS... I'm having difficulties with the session:
In some debugging I found that the middleware that starts and stores the session data does not execute in the plugin routes, however manually adding the middleware works for the custom routes but breaks OctoberCMS due to a decryption error - which I think that's related to the Encrypt Cookies middleware.
Is there something potentially missing in the config for this to work?

Any help would be greatly appreciated.

**Comment by grahambrown11** [comment]
Here is some sample code to show and reproduce the issue I'm having
```
Route::get('test-session', function() {
    $orig = Session::get("sales_process_id");
    if (Request::has("id")) {
        Session::put("sales_process_id", Request::get("id"));
    }
    return "Orig:  {$orig}, Current: " . Session::get("sales_process_id");
});
```
The 1st time going to `/test-session?id=123` I'd expect the output `Orig: , Current: 123` and then going to `/test-session?id=456` I'd expect the output `Orig: 123, Current: 456`, however Orig is always blank.

If I add the following to the route, then the session is persisted
```
->middleware([
    "Illuminate\Cookie\Middleware\EncryptCookies",
    "Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse",
    "Illuminate\Session\Middleware\StartSession",
    "Illuminate\View\Middleware\ShareErrorsFromSession",
    "Illuminate\Routing\Middleware\SubstituteBindings",
]);
```
(I got from the web middleware group defined in `~/vendor/october/rain/src/Foundation/Http/Kernel.php`)
However now browsing to the home page I get `unserialize(): Error at offset 0 of 40 bytes` with the stack:

CALLED CODE | DOCUMENT | LINE
 -- | -- | --
 unserialize(…) | ~/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php | 149
 Illuminate\Encryption\Encrypter->decrypt(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php | 103
 Illuminate\Cookie\Middleware\EncryptCookies->decryptCookie(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php | 83

@daftspunk I'm hoping you may point me in the right direction as you seem to have a far better understanding of Laravel than I do.

Thanks

**Comment by daftspunk** [comment]
Laravel broke this in version 5.5 so you need to explicitly state that your route uses the `web` middleware. Eg:

```
Route::any('{slug}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?')->middleware('web');
```

**Comment by daftspunk** [comment]
Updated in ce09493761897b798e9c7dd1ee560823d10fb3f9

**Comment by grahambrown11** [comment]
Thank you
